#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE USER keycloak WITH PASSWORD '${POSTGRES_PASSWORD}';
	CREATE DATABASE keycloak OWNER keycloak;
	CREATE USER hapi WITH PASSWORD '${POSTGRES_PASSWORD}';
	CREATE DATABASE hapi OWNER hapi;
EOSQL
