/**
 * fhir-clinical-mcp
 * MCP server for FHIR Clinical (curated MCP subset)
 *
 * Generated by openapi-mcp-generator. Entry point: starts the stateless
 * Streamable HTTP MCP server. See src/mcp-server.ts for the security model.
 */
export * from './mcp-server.js';
export * from './oauth-resource-server.js';

import { startServer } from './mcp-server.js';

startServer();
